server:
  port: 8080

spring:
  datasource:
    username: rain
    password: rain
    url: jdbc:mysql://192.168.27.103:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.project.rain.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
